# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'GitHubClientExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitHubClientExample
  pod 'GithubApiClient', '1.0.1'#:path => '../'
#  pod 'GithubApiClient/Networking'#, :path => '../'

  target 'GitHubClientExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
